### PR TITLE
Delete overcloud-resource-registry-puppet.j2.yaml

### PR DESCRIPTION
**Pull request by EmilienM**
This file should not be useful since you define the service under resource_registry in your environment:
https://github.com/dell/tripleo-powerflex/blob/master/environments/powerflex-ansible/powerflex-ansible.yaml#L2-L5

If it doesn't work, then there is a bug in TripleO and we need to fix it.

### CODE REVIEW

**Comment by jproque-dell** [comment]
> This file should not be useful since you define the service under resource_registry in your environment:
> https://github.com/dell/tripleo-powerflex/blob/master/environments/powerflex-ansible/powerflex-ansible.yaml#L2-L5
> 
> If it doesn't work, then there is a bug in TripleO and we need to fix it.

Agree, but we need to define somewhere the action which has to be taken when the service is not enabled. See below:
    OS::TripleO::Services::PowerFlexLIA: OS::Heat::None
    OS::TripleO::Services::PowerFlexMDM: OS::Heat::None
    OS::TripleO::Services::PowerFlexSDC: OS::Heat::None
    OS::TripleO::Services::PowerFlexSDS: OS::Heat::None

For now, this definition is a dell environment file but would it be possible to include it upstream into the overcloud-resource-registry that comes along TripleO

**Comment by EmilienM** [comment]
> > This file should not be useful since you define the service under resource_registry in your environment:
> > https://github.com/dell/tripleo-powerflex/blob/master/environments/powerflex-ansible/powerflex-ansible.yaml#L2-L5
> > If it doesn't work, then there is a bug in TripleO and we need to fix it.
> 
> Agree, but we need to define somewhere the action which has to be taken when the service is not enabled. See below:
> OS::TripleO::Services::PowerFlexLIA: OS::Heat::None
> OS::TripleO::Services::PowerFlexMDM: OS::Heat::None
> OS::TripleO::Services::PowerFlexSDC: OS::Heat::None
> OS::TripleO::Services::PowerFlexSDS: OS::Heat::None
> 
> For now, this definition is a dell environment file but would it be possible to include it upstream into the overcloud-resource-registry that comes along TripleO

If the environment has these definitions, there is no need to add it upstream.
Just define them in your environments and you should be fine.

**Comment by jproque-dell** [comment]
Workflow is the following.
The mapping for disabled services is defined into a dell environment file where other parameters are also.
If the user has enabled PowerFlex backend then we add the powerflex-ansible environment file which maps the services to the appropriate heat templates, this action overwrites the default actions.
If the User has chosen to go with another backend, then the default actions will be taken.

As you can understand, the order we pass th environment file when deploying is crucial here. That said, the dell-environment file which contains default is placed first then the powerflex-ansible or other vendor environement file is placed second.

Are we good?

**Comment by EmilienM** [comment]
> Workflow is the following.
> The mapping for disabled services is defined into a dell environment file where other parameters are also.
> If the user has enabled PowerFlex backend then we add the powerflex-ansible environment file which maps the services to the appropriate heat templates, this action overwrites the default actions.
> If the User has chosen to go with another backend, then the default actions will be taken.
> 
> As you can understand, the order we pass th environment file when deploying is crucial here. That said, the dell-environment file which contains default is placed first then the powerflex-ansible or other vendor environement file is placed second.
> 
> Are we good?

why would you disable the services for our users? If they use your templates, aren't they going to deploy your services anyway? In any case, the overcloud registry file is not needed. You can solve these problems via environment files in the right order.

**Comment by jproque-dell** [comment]
Because we use the same roles_data.yaml file for every deployment and services are defined even if they are not enabled (for example on controllers and compute nodes).
I concur with the deletion of the file though.

**Pull request merged**
